# Generated by Django 4.1.3 on 2022-11-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genres_movie_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
