# Generated by Django 4.1.3 on 2022-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile_path',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
