# Generated by Django 4.1.3 on 2022-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
