# Generated by Django 4.1.3 on 2022-11-21 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieroomuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='movieroomuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
